### ISSUE TITLE
Unterrichtsausfall in Zeitenbox darstellen

### ISSUE THREAD

**Issue by Antimon2000** [wingchunforum/Website#16]
Trainingseinheiten, die in die Zeit eines Unterrichtsausfalls fallen, sollen mit dem Vermerk aufgeführt werden, dass sie nicht stattfinden.

**Comment by Antimon2000** [comment]
Einheiten, die vom Ausfall betroffen sind, werden angezeigt, aber durchgestrichen. Die Zeit, die die Dauer bis zum Beginn der jeweiligen Einheit angibt, wird durch einen roten Text „fällt aus“ ersetzt.

**Comment by boeckers** [comment]
Wird korrekt dargestellt, sehr schön.

**Comment by boeckers** [comment]
Mit den Ausrufezeichen ist es noch etwas auffälliger. Find ich ganz gut.
