### ISSUE TITLE
Eltern-Kind-Kurs vorläufig entfernen

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#17]
Die Idee den Eltern-Kind-Kurs als eine Art Probetraining anzubieten funktioniert so noch nicht gut. Evtl. arbeiten wir dafür aber ein neues Konzept aus. Wäre es daher möglich, den EKK vorläufig von der Angebotsseite und der Preisseite zu nehmen, jedoch so, das wir ihn bei späteren Bedarf wieder einsetzen können?  

Dazu könnte die zusätzliche Beschreibung unter "Kostenlose Einführung..." entfallen. Die Kachel "Probetraining" müsste dann über die ganze Spalte gehen. Auf der Preisseite würde die letzte Zeile entfalten.

**Comment by Antimon2000** [comment]
Kann ich machen. Die Kachel Probetraining würde dann so aussehen wie die, die im Abschnitt „Training & Unterricht“ zu finden sind.

**Comment by boeckers** [comment]
Ja, super, so hatte ich das gedacht,

**Comment by Antimon2000** [comment]
Gefällt mir sogar besser mit dem einheitlichen Layout.

**Comment by boeckers** [comment]
Ja, mir auch, ist klarer. Allerdings muss der Text über dem Probetraining noch weg oder angepasst werden, da steht der EK-Kurs nämlich noch drin.

**Comment by Antimon2000** [comment]
Die Seite ist ohne den Text kein bisschen schlechter verständlich und habe ihn deshalb entfernt.

**Comment by boeckers** [comment]
Ja, so ist es super.
