### ISSUE TITLE
Aktuelles und Rundschreiben

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#27]
Wir müssen so schnell wie möglich das Rundschreiben und den Aktuelleskasten aktualisieren, damit sowohl im Rundschreiben, als auch in dem Kasten auf der Startseite die Sommerpause angekündigt wird. Macht Pierre das schon oder machst du das noch einmal?

**Comment by Antimon2000** [comment]
Steht schon auf meinem Zettel und ist für später geplant. Diesmal mach ich das noch!

**Comment by boeckers** [comment]
Huch, guten Morgen. Vielen Dank!
