### ISSUE TITLE
Captchas schwer lesbar

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#29]
Mittlerweile zum zweiten Mal beschwert such jemand darüber, dass die Captchas unglaublich schwer zu lesen seien und etliche Versuche zum Versenden einer Probetrainingsanfrage unternommen wurden. Kann/muss man da etwas ändern?

**Comment by Antimon2000** [comment]
In welchem Zeitraum sind die beiden Beschwerden denn eingegangen? Und haben diejenigen gesagt, mit was für Geräten und Browsern sie das Captcha nicht lesen konnten? Das eingesetzte System ist eigentlich recht weit verbreitet. Ich schau aber mal nach, ob es evtl. Updates gibt, die das Problem beheben.

**Comment by boeckers** [comment]
Einmal vor und einmal nach meinem Urlaub, also ca. 4 Wochen dazwischen. Ich habe selbst mal nachgesehen. Die Hausnummern lasen sich immer gut lesen, dir meisten Schriften auch, aber eine Art von Buchstabenfolgen ist dabei, die sind in der Tat unmöglich. Bei einem Refresh erscheinen dann wirklich sehr viele davon hintereinander. Insofern kann ich die Beschwerde nachvollziehen.

**Comment by Antimon2000** [comment]
Da technisch alles funktioniert, fürchte ich, müssen wir noch auf weitere Beschwerden warten und hoffen, dass die zukünftigen Captcha-Serien wieder etwas lesbarer sind. Für so wenige Leute lohnt sich der Aufwand meines Erachtens nicht – zumindest nicht bei der Menge an offenen Tickets, die schon eine Ewigkeit hier rumliegen.

**Comment by boeckers** [comment]
Denke auch, es hätte sich nur gelohnt, wenn wir einfach Einstellungen hätten vornehmen können.
