### ISSUE TITLE
Unterseite für Jugendgruppe anlegen

### ISSUE THREAD

**Issue by wingchunforum** [wingchunforum/Website#3]

**Comment by boeckers** [comment]
Textvorschläge für Kinder, sowie Jugendseite befinden sich auf dem WIKI unter http://wiki.wingchun-forum.de/doku.php?id=talk:wiki:website

**Comment by boeckers** [comment]
Seite „Unser Team“: Die Bezeichnung „Kindertrainerin“ muss „Kinder- und Jugendtrainerin“ heißen, um die Ansprache des Zielpublikums konsequent zu machen. 

Das zweite Menü muss um den Punkt „Für Jugendliche“ erweitert werden in der Reihenfolge von oben nach unten: Wing Chun - Für Erwachsene - Für Jugendliche - Für Kinder

Seite „Wing Chun“: Die weiterführenden Links müssen um den Link „Für Jugendliche“ erweitert werden.

Seite „Angebot“ muss zwischen „Für Erwachsene“ und „Für Kinder“ um „Für Jugendliche ergänzt werden. Problem: Foto (evtl. kaufen?)

**Comment by boeckers** [comment]
Zweites Problem: die Bezeichnung "Jugendliche" stimmt für die Altersgruppe 9-13 nicht. Wir brauchen eine passende Bezeichnung für Kinder 5-8 und Kinder 9-13. Besprechung u.a. dazu mit den betr. Trainerteam am 2.4.15

**Comment by Antimon2000** [comment]
- [x] Seite „Unser Team“: Die Bezeichnung „Kindertrainerin“ muss „Kinder- und Jugendtrainerin“ heißen

**Comment by Antimon2000** [comment]
Hat das Treffen mit dem Trainerteam bzgl. der Namensgebung irgendetwas ergeben? Ich befürchte, es gibt schlicht keine einheitliche Bezeichnung für diese Altersgruppe. Wir könnten das Menü schlicht beibehalten und auf der Seite „Für Kinder“ auf beide Altersgruppen getrennt eingehen. Bliebe noch die Frage, ob sich ein Dreizehnjähriger evtl. nicht ernst genommen fühlt, wenn er sich auf der Kinderseite angesprochen sieht. Ich kann mich da leider nicht mehr hineinversetzen.

**Comment by boeckers** [comment]
Leider auch nicht. Neben 'Fantasienamen' wie Minni oder ähnlichem nur konkrete Altersangaben wie Kinder (5-8) und Kinder (9-13) oder Kids (9-13). Es gibt also leider keine gute Lösung für das Problem.

**Comment by Antimon2000** [comment]
Dann überleg ich mir weiter Texte für die Seite und du überlegst dir, mit welcher Namensgebung wir dann arbeiten werden? Eine Entscheidung müssen wir auf jeden Fall bald treffen. Konkrete Altersangaben kann ich mir auch gut vorstellen. Allenfalls das Schema „Für <Gruppe>“ muss dann angepasst werden; ggf. einfach in „<Gruppe>“.

**Comment by boeckers** [comment]
Ich grübel schon die ganze Zeit, mein Vorschlag wäre: Erwachsene, 9-13 Jahre, 5-12 Jahre. In den Überschriften und auf der Zeitenseite wäre es dann "Wing Chun für 9-13 jährige" bzw. "Wing Chun für 5-12 jährige". Evtl. sollten wir dann, um das Schema durchzuhalten auf der Zeitenseite auch die Zeiten für Erwachsene mit "Wing Chun für Erwachsene" kennzeichnen.

**Comment by Antimon2000** [comment]
Ich hab nun mal testweise ausprobiert, ob wir den Zusatz „Für“ im Menü behalten können und es scheint zu klappen:

- Für Erwachsene
- Für Kinder (9–13 J.)
- Für Kinder (5–8 J.)

**Comment by boeckers** [comment]
Wäre am leichtesten Verständlich, hat nur den Nachteil, dass wir dann die 13-Jährigen als Kinder ansprechen. Kann ich schwer sagen, ob das ok ist.

**Comment by boeckers** [comment]
Der Tag der offenen Tür wurde im Ultimo und im Wochenspiegel (!) angekündigt. Infolge dessen kommen nun schon erste Anfragen bzgl. der Jugendgruppe.

**Comment by Antimon2000** [comment]
Beim nächsten Mal bitte ein Datum angeben, zu dem das Ticket bearbeitet sein muss/sollte. Dann kann ich besser planen.

In diesem Fall dauert es übrigens so lange, weil die Texte im Wiki kaum Informationen enthalten, wir aber das Schema von 2 x 4 Kurztexten befüllen müssen/wollen. Ich schlage vor, dass wir den Abschnitt "Kann ich Wing Chun lernen?" auf allen Zielgruppenseiten (Erwachsene bis kleine Kinder) beibehalten und nur den Teil "Was erwartet mich?" anpassen. Die Frage ist also: Welche 4 Kerninformationen wollen wir auf der Seite unterbringen? Herausgelesen habe ich neben den Dingen, die bereits im ersten Seitenabschnitt stehen die 4 folgenden neuen Informationen:

 - sicheres Auftreten
 - sich selbst und andere schützen
 - verschiedene Übungsabläufe
 - auch Konzentration und geistige Stärke im Fokus

Insbesondere den letzten Punkt halte ich für die Zielgruppe nicht für allzu wichtig. Finden wir da noch etwas Besseres?

**Comment by boeckers** [comment]
Ein fixes Datum gibt es natürlich nicht. Ich bin auf überrascht, dass der WoSpi schon jetzt die Ankündigung gedruckt hat, das sollte so nicht sein. Ist aber besser als gar nicht.

Den "Wer kann Wing Chun lernen"-Teil beizubehalten ist gut, wir sollten bei den Kindern den Punkt "Wir unterrichten Frauen und Männer..." evtl. in "... Mädchen und Jungen..." ändern.

Vorschlag für vier Punkte: 
- sich und andere Schützen
- Selbstsicheres Auftreten lernen und so verhindern überhaupt angegriffen zu werden
- Lernen gefährliche Situationen zu erkennen und mit ihnen umzugehen
- in Alltagssituationen wie Streitereien cool zu bleiben


-

**Comment by Antimon2000** [comment]
Habe die Seite nun angelegt und die Informationen recht notdürftig eingefügt. Können wir das erstmal so lassen und wollen wir die Jugendgruppe noch irgendwie anders bewerben?

**Comment by boeckers** [comment]
Ich finde die Seite an sich ganz gut so. Allerding muss die Angebotsseite entsprechend angepasst werden. Da taucht dann das Problem mit dem Foto auf. 

Ansonsten werden wir versuchen die Gruppe durch redaktionelle Teile im Lüttbecker und Ultimo zu bewerben. Allerdings erst, wenn,dir Website fertig ist. Bisher haben sich fünf Interessenten gemeldet, was,recht viel ist. Nächste Woche Mi, am 22. startet die Gruppe.

**Comment by boeckers** [comment]
Auf der Seite "Wing Chun" im Menü unten "Weiter" muss die Seite "Unterricht für Kinder (9-13 J.)" auch noch ergänzt werden.

**Comment by Antimon2000** [comment]
- [ ] Unterricht für Jugendgruppe auf Angebotsseite bewerben
- [ ] On-page-Navigation der Seite "Wing Chun" um Verweis auf Jugendgruppe ergänzen

**Comment by Antimon2000** [comment]
Ich hab nun insgesamt sicher schon 30 Minuten nach einem Bild gesucht, das kostenlos und zur kommerziellen Nutzung freigegeben ist – vergeblich. Hast du noch irgendwo brauchbare Bilder?

**Comment by boeckers** [comment]
Das habe ich befürchtet. Nein, ich habe auch har keine brauchbaren Bilder und habe ebenfalls schon vergeblich gesucht. Gibt es evtl. welche zu kaufen? Hast du eine Idee, wo ich vielleicht noch suchen könnte?

**Comment by Antimon2000** [comment]
Ich habe nun ein Bild genommen, das als Platzhalter okay sein müsste. Langfristig müssen wir aber eins finden, das für die Zielgruppe besser passt.

Neues Ticket #19 erstellt.
