### ISSUE TITLE
Rundschreiben Februar ohne Link

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#33]
Anders als zuvor ist der Aktuelles-Kasten unten links für das Februar-Rundschreiben nur durch die Überschrift des Kastens verlinkt. Bisher hatten wir immer noch den "Mehr lesen.."-Link. Ist das Absicht, weil der Link nicht passt? Der Link in dem Kasten wird gern übersehen. Vielleicht hinzufügen?

**Comment by Antimon2000** [comment]
Auch das war der Umstrukturierung geschuldet! Ist hinzugefügt!
