### ISSUE TITLE
Kontaktformular defekt!

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#35]
Ein Interessent hat mich darauf aufmerksam gemacht, dass unser Kontaktformular gar nicht funktioniert. Ich habe es getestet, geht tatsächlich nicht. Es erscheint keine Meldung, keine Nachricht wird versendet, auch keine Kopie. Das Formular ist natürlich äusserst wichtig.

**Comment by Antimon2000** [comment]
Schau ich mir sofort an!

**Comment by Antimon2000** [comment]
Hast du ggf. das Passwort der info@ Mail-Adresse geändert?

**Comment by boeckers** [comment]
Das ist möglich, ich schaue kurz nach. Mein Ebay-Konto wurde gehackt mit beachtlichem finanziellen Schaden für einige Käufer. Polizei ermittelt. Da habe ich einige Passwörter geändert. Ich prüfe das, 5 min bitte.

**Comment by Antimon2000** [comment]
Ja, wurde geändert. Schreib mir mal eine SMS mit dem neuen Passwort.

Oh mann, gehackt? Was ist denn da passiert?

**Comment by boeckers** [comment]
Ja, habe ich, habe nicht daran gedacht, sorry. Wie lasse ich dir das neue am besten zukommen? SMS?

**Comment by boeckers** [comment]
Hat sich überschnitten, sorry. Ja, lange und spannende Geschichte, aber klarer Angriff gegen mich, meine Schäden wurden behoben, kein finanziellen Schaden für mich. Aber die betroffenen Käufer haben ihr Geld auf nicht registrierte Konten überweisen und somit keinen Käuferschutz. Harte Sache. SMS kommt.

**Comment by Antimon2000** [comment]
Formular geht wieder.

Na super. Angriff auf Dich als Person oder einfach "nur" Kollateralschaden? Kannst du ausschließen, dass dein Rechner nicht kompromittiert wurde?

**Comment by boeckers** [comment]
Haben wir diese Adresse incl. Passwort evtl. auch für den WIKI in Gebrauch? Muss das da auch geändert werden?

**Comment by Antimon2000** [comment]
Gerade nochmal nachgesehen, im Wiki war die Adresse keinem Nutzer zugeordnet.
