### ISSUE TITLE
Anpassen der Unterrichtszeiten

### ISSUE THREAD

**Issue by wingchunforum** [wingchunforum/Website#4]
Einpflegen von

- SNT-Gruppe
- Kindergruppe
- Jugendgruppe

**Comment by boeckers** [comment]
Die Gruppe am Montag wird einfach bei den Trainingszeiten unter Wing Chun ergänzt (18 bis 19.30) und gilt ab sofort. Die Zeit soll auch in der Zeitenbox angezeigt werden.

Wing Chun für Kinder (5-8) verschiebt sich auf 16-17 Uhr.
 Wing Chun für Jugendliche (9-13) wird ebenfalls Mittwoch um 17 bis 18 Uhr ergänzt. 
 Beides ist ab dem 22. April gültig und müsste dann ganz normal bei den Zeiten in der Zeitenbox angezeigt werden.

**Comment by Antimon2000** [comment]
Unterrichtszeiten für die Montagseinheit (18.00 – 19.30 Uhr) eingetragen
- auf der Seite Unterrichtszeiten
- in der Zeitenbox

Letzteres sollte am Donnerstag ab 11 Uhr auf der Website überprüft werden.

**Comment by boeckers** [comment]
Wird am Donnertag dem 2.4. korrekterweise nicht angezeigt, weil Montag ein Feiertag ist.

**Comment by Antimon2000** [comment]
Die anderen Zeiten können am 8. April ab 18 Uhr eingetragen werden, da es ab diesem Zeitpunkt nicht mehr zu Irritationen mit dem Stundenplan kommen kann.

**Comment by Antimon2000** [comment]
Unterrichtszeiten für die Kindergruppen eingetragen
- auf der Seite Unterrichtszeiten
- in der Zeitenbox
