### ISSUE TITLE
Seite „Unser Team“ erneuern

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#5]
Bilder evtl. wechselseitig? Cai braucht ein neues Foto.

**Comment by boeckers** [comment]
- Nicho muss auf die Seite als SNT-Ausbilder
- Martin ebenfalls als "Kinder- & Jugentrainer"

**Comment by boeckers** [comment]
Weniger dringend als die Issues #6 und #7.

**Comment by Antimon2000** [comment]
Liegt bereits ein neues Foto für Cai vor?

**Comment by boeckers** [comment]
Laut Nicho liegt dir ein Foto von ihm vor, einen Text habe ich erneut von ihm angefordert.

Von Martin habe ich Text und Foto angefordert.

Vom Cai liegt kein Foto vor, er  weiß auch noch nicht, dass wir ein neues brauchen. Eine Mail diesbzgl. hatte er nicht beantwortet. Ich spreche ihn an, wenn ich ihn das nächste mal sehe.

**Comment by Antimon2000** [comment]
Sehr schön, bis dieses Ticket dran ist, müssten dann ja auch die erforderlichen Texte und Fotos da sein!

**Comment by boeckers** [comment]
Habe an alle eine Aufforderung per SMS gesendet Text, Foto bzw. beides an florian@wingchun-forum.de zu senden am 4.4.

**Comment by boeckers** [comment]
Martin hat einen Text und Foto fertig. Als Ansprechpartner für die Jugendgruppe benötigt er auch eine Emailadresse: martin@wingchun-forum.de

**Comment by Antimon2000** [comment]
Habe mal die Adresse abgeändert, so dass sie nicht von irgendwelchen Spam-Crawlern gefunden wird. Ansonsten.

**Comment by boeckers** [comment]
Wenn wir Martin als Kinder- und Jugendtrainer mit auf der Liste haben könnte Lisas Text "Ich leite zuammen mit Verena das Kindertraining." besser "..zusammen mit Verena und Martin..." lauten.

**Comment by Antimon2000** [comment]
Von Martin habe ich sowohl Text und Foto bekommen. Nichos Text fehlt. Cais Text und Bild fehlen ebenfalls.

Bis die Informationen vorliegen, können wir hier kurz planen, was auf der neuen Teamseite zu finden sein soll. Portraits, Kurzvorstellungen und Rollenbeschreibungen sind sicherlich notwendig. Wie können wir im Besucher zusätzlich Vertrauen in unsere Kompetenz wecken? Innerhalb welcher Grenzen wäre es erwünscht, zu den jeweiligen Teammitgliedern Kontakt aufnehmen zu können? Benutzen die Kindertrainer ihre E-Mail-Adressen zur Kontaktaufnahme mit den Eltern? Sollen auch inaktive Teammitglieder einen (weniger prominenten) Platz haben (z.B. Ulrike)?

**Comment by Antimon2000** [comment]
Martin findet man nun auf der Teamseite.

**Comment by boeckers** [comment]
Cai scheint mir im Urlaub zu sein, jedenfalls erreiche ich ihn gar nicht. Wenn ich ihn sehe sage ich erneut Bescheid. Nicho weiß bescheid, ihm fällt wohl nur kein Text ein.

Ich denke gänzlich inaktive Teammitglieder sollten nicht rauf, die werden ja nicht als Ansprechpartner wahrgenommen. Ebenso sollen die Assistenten nicht auf die Seite, damit sie sich in der Assistenzphase orientieren können. Wenn sie dann sagen, zu unterrichten macht ihnen Spaß,sie bleiben dabei und werden Ausbilder, setzten wir sie drauf. 

Zur Zeit sind 11 Personen im Team, ich habe Kapazität von z.Zt. 12. Es käme also irgendwann evtl. noch eine Person hinzu. Ich denke solange wir noch keine weiteren Standorte haben genügt das auch. 

Da alle externen Anfragen von mir bearbeitet werden, hatten wir uns ja dafür entscheiden, dass alle Anfragen an die info-Adresse gehen. Ich denke, das sollte zu Zeit auch so bleiben. Die Eltern der Kinder z.B. erhalten die Adressen von Lisa und Verena dann direkt. Wenn Anfragen direkt an andere Ausbilder gingen würde das unübersichtlich und für mich unberechenbar. Ich denke auch die Kontaktadressen der Mitglieder sollten wir vorerst nicht auf die Seite setzen.

**Comment by boeckers** [comment]
Kannst du in dem Text von  Martin "[...] mich gerade zum Ausbilder für die Siu Nim Tau fortlden [...]" ändern in ""[...] mich gerade zum Ausbilder für die Siu-Nim-Tao-Stufe fortlden [...]"?

Zudem haben wir in unserem Glossar und den Programmen "Tao" in "Siu Nim Tao" immer mit "o" geschrieben. Ich denke das sollten wir auch auf der Teamseite beibehalten. (Betrifft Text Martin, Cai und Tho).

**Comment by boeckers** [comment]
Ich habe mit mal Teamseiten von verschiedenen Firmen angesehen und vom Aufbau sind die alle ähnlich, wie unsere. Einen sehr seriösen Eindruck macht es, wenn die Fotos einheitlich und professionell gemacht sind. Vielleicht sollten wir das Team zusammentrommeln und einen Fototermin machen, bei dem für jeden ein kleines Foto und ein großes Gruppenfoto für das Panorama gemacht wird. Das gehörte dann in #9.

**Comment by Antimon2000** [comment]
Wichtig ist ja nicht, alle Fotos am selben Ort zu machen, sondern dass alle Fotos dasselbe Setting haben: Ich schlage vor
 - gleichfarbiger Hintergrund
 - jedes Teammitglied trägt sein WCF-Shirt
Wichtig ist, dass das Setting schnell und einfach reproduziert werden kann.

Mir ist beim Ansehen der Teamseite außerdem der Gedanke gekommen, dass wir vor allem Leute mit Wing-Chun-Erfahrung vergraulen könnten. Wenn jemand die Abkürzungen "SNT" und "CK" kennt, fragt der sich, was er bei uns soll, wenn alle Ausbilder bis auf eine Ausnahme nur SNT/CK gelernt haben bzw. unterrichten können. Das sollten wir ggf. einfach umbenennen (z.B. in Ausbilder I, Ausbilder II, etc.) oder es komplett weglassen.

**Comment by boeckers** [comment]
Ja, genau so sehe ich es auch, der Anfang wäre die Bezeichnungen zu ändern. Diese wären dann Assistent, Kinder- und Jugendtrainer, Ausbilder I, Ausbilder II, Ausbilder III, Ausbilder IV, Lehrer. Mein Vorschlag wäre die Fotoproblematik in die Aufgabe "Bebilderung" zu verschieben und Anzugehen, wenn alle Fotos anstehen.

**Comment by boeckers** [comment]
Oder wir fragen Pierre einfach, ob er Kamera und Blitz mitbringt und wir machen alle Fotos nach und nach beim Training vor der weissen Wand. Soll ich ihn ansprechen?

**Comment by Antimon2000** [comment]
Habe die Bezeichnungen angepasst.

Ja, frag doch Pierre mal. Am besten stellt ihr euch dann 2–3m vor eine weiße Wand und er fotografiert mit Tiefenunschärfe (dann erkennt man nämlich auch die Wandstruktur nicht mehr). Vorher nur noch für eine vernünftige, gleichmäßige Beleuchtung sorgen und schon haben wir vollkommen ausreichende Ausbilderfotos bei minimalem Aufwand.

**Comment by boeckers** [comment]
Pierre übernimmt das gerne und macht heute (22.4.) oder morgen Probeaufnahmen zum Testen von Licht etc.

**Comment by Antimon2000** [comment]
Sehr gut! Und Farbfotos sollten es sein. Im Nachhinein können wir immer noch entscheiden, ob s/w besser passt.

**Comment by boeckers** [comment]
Pierre hat heute Probefotos gemacht, mit falschen Motiv (Thore), aber in dem gefragten Stil. Sendet er die demnächst zu, damit du auch nochmal sagen kannst, worauf er achten soll, wenn er dann die richtigen Fotos schießt.

**Comment by boeckers** [comment]
Morgen, am 28.4. macht Pierre mit Tho gemeinsam erneut Probeaufnahmen, diesmal mit umfangreicherem Equipment. Bisher ist er unzufrieden.

**Comment by boeckers** [comment]
Probeaufnahmen und Aufnahme von Cai sind gemacht. Hoffentlich brauchbar.

**Comment by Antimon2000** [comment]
Damit hatte ich ja jetzt am wenigsten gerechnet ;-)

**Comment by boeckers** [comment]
Ja, wir dachten, das machen wir lieber gleich, auch wenn Pierre sich nun noch nicht mit dir absprechen konnte. Jedes Foto ist besser als das jetzige.

**Comment by Antimon2000** [comment]
Welche Ressourcen liegen bereits vor?

Name | Text | Neues Foto
--------- | ------ | ------
Lars     |   ✓   |
Flo       |   ✓   |
Tho      |   ✓   |
Cai       |         |
Verena |   ✓   |
Lisa      |   ✓   |
Nicho    |        |
Martin   |   ✓   |

**Comment by boeckers** [comment]
Warum hat Cai keinen Text? Ist der nicht schon auf der Seite? Nicho habe ich erneut Bescheid gegeben. Martin organisiert ein T-Shirt. Einen großen Teil der Fotos wollen wir auf dem Teamtreffen am 9.5. machen.

**Comment by Antimon2000** [comment]
Huch, Häkchen vergessen. Gut, das ist ja schon bald. Kriegt ihr das dann so hin, dass nicht alle anderen Leute demjenigen zugucken, von dem gerade das Foto gemacht wird? Sonst haben wir am Ende lauter Bilder von Leuten, die tierisch verkrampft in die Linse schielen. Zumindest wüsste ich, dass das bei mir so wäre ;-) Vielleicht kann man ja einen Sichtschutz aufbauen.

**Comment by boeckers** [comment]
Ja, ich werde versuchen eine entsprechend entspannte Atmosphäre zu kreieren... vielleicht hilft Bier? :-)

**Comment by boeckers** [comment]
Die Fotos können nun doch nicht am Samstag (9.5.) gemacht werden, da Pierre verhindert ist und müssen in den Wochen danach gemacht werden.

**Comment by Antimon2000** [comment]
Welche Ressourcen liegen bereits vor?

Name | Text | Neues Foto
--------- | ------ | ------
Lars     |   ✓   |
Flo       |   ✓   |
Tho      |   ✓   |
Cai       |   ✓   |   ✓
Verena |   ✓   |   ✓
Lisa      |   ✓   |   ✓
Nicho    |        |   ✓
Martin   |   ✓   |   ✓
Pierre   |         |

**Comment by boeckers** [comment]
Martin muss zusätzlich als Ausbilder I gekennzeichnet werden. Thore muss als Ausbilder I auf die Seite. Er ist angewiesen einen Text zu schreiben und dir zuzusenden.

**Comment by Antimon2000** [comment]
- [x] Martin muss zusätzlich als Ausbilder I gekennzeichnet
- [ ] Thore muss als Ausbilder I auf die Seite

**Comment by Antimon2000** [comment]
Die Teamseite wirkt durch die neuen Fotos aufgeräumter und verleiht dem Team ein professionelleres Auftreten. Mein Foto muss jedoch noch erneuert bzw. entfernt werden.

**Comment by Antimon2000** [comment]
Da die Teamseite vor der Umstellung auf Bootstrap ohnehin nicht mehr umgestaltet wird, schließe ich dieses Ticket erstmal.
