### ISSUE TITLE
Seite „Für Erwachsene“ nach unserem Schema aufbauen

### ISSUE THREAD

**Issue by boeckers** [wingchunforum/Website#6]
Textvorschlag findet sich hier: http://wiki.wingchun-forum.de/doku.php?id=talk:wiki:website

**Comment by Antimon2000** [comment]
Habe Texte entworfen, Icons ausgewählt und die Seite hochgeladen. Bitte Feedback, falls ich etwas ändern soll. Wenn alles stimmt, kann ich das Ticket schließen und mich der Jugendseite widmen.

**Comment by boeckers** [comment]
Stimmt alles, gefällt mir sehr gut. Vor allem der Text über Prüfungen und der über den niedrigen Preis sind genial.

**Comment by Antimon2000** [comment]
Freut mich!
